### ISSUE TITLE
Stable for production usage?

### ISSUE THREAD

**Issue by fzyzcjy** [facebookincubator/profilo#109]
Hi thanks for the wonderful lib! I wonder whether it is stable to be integrated into production app? Since it is under "incubator" and the documentation is a bit short I am worried about it.

**Comment by aandreyeu** [comment]
Hi, thanks for the feedback! It's stable for production use and used internally by Meta apps. It's under "incubator" as the open source offering is still "experimental" as we gauge the interest to the library and community feedback. There is no committed for long term support.

**Comment by fzyzcjy** [comment]
hank you!
