### ISSUE TITLE
dex version 39 can not get stacks

### ISSUE THREAD

**Issue by xnfreedom** [facebookincubator/profilo#112]
While parsing trace file to get stacks, the assert in file profilo/symbols/apk_symbols.py will case parsing stop.
code line is as blow:
assert dex_version <= DEX_FILE_VERSION_MAX
got dex_version is 39, and DEX_FILE_VERSION_MAX is 38.
If I comment this line, then there's no any output.
used command: python3 -m profilo.workflow_demo ~/Code/github/profilo/python/override-main-0-31630-2022-4-1T14-30-33-H2KqMG_v50I.log  stacks ~/Code/github/profilo/python/pDemo.apk

**Comment by yukonfb2** [comment]
The issue with no stacks might be related to your Android version - this source supports call stacks up to Android 9. Which version are you using?
