### ISSUE TITLE
Can't run workflow_demo.py

### ISSUE THREAD

**Issue by Leland-Takamine** [facebookincubator/profilo#13]
The following command fails:

```
$ python3 profilo/workflow_demo.py
Traceback (most recent call last):
  File "profilo/workflow_demo.py", line 18, in <module>
    from .importer.trace_file import TraceFile
ModuleNotFoundError: No module named '__main__.importer'; '__main__' is not a package
```

**Comment by BurntBrunch** [comment]
The correct way to run it is `python3 -m profilo.workflow_demo` from within the python directory, within an environment that contains everything in requirements.txt.

I'll make sure we document this explicitly.

**Comment by BurntBrunch** [comment]
This has been fixed in the docs.

Please take a look at https://facebookincubator.github.io/profilo/docs/trace-processing.html and let us know if the process is still unclear.
