### ISSUE TITLE
Pulling trace file from real device get error

### ISSUE THREAD

**Issue by AndrejLee** [facebookincubator/profilo#21]
I got this error when pulling trace file from my project deployed on my phone:
`File /data/data/com.example.cpu10152_local.threadpool/run-as: exec failed for find Error:Permission denied was moved. Retrying...`
But on emulator, I could pull log file successfully.
My device: Asus ZenFone Go

**Comment by BurntBrunch** [comment]
Does your device have a `find` command? Try the following:

```
adb shell
$ run-as com.example.cpu10152_local.threadpool
$ find cache
```
