### ISSUE TITLE
Running Stacks and Blocks analyzing return no value

### ISSUE THREAD

**Issue by AndrejLee** [facebookincubator/profilo#22]
After getting log file from my project deployed on emulator, I run stacks and blocks analyzing but got no result (0 is stacks items size):

![image](https://user-images.githubusercontent.com/22562428/40404119-502cf394-5e80-11e8-9f64-fe21f02d121f.png)

Meanwhile, I could get analyzed graph in syscounters:

![image](https://user-images.githubusercontent.com/22562428/40404180-a55423a6-5e80-11e8-8db7-cadb733fa408.png)

**Comment by BurntBrunch** [comment]
What Android version were these from? Stacks would work best from 6.x.

Systrace collection is disabled in master right now due to bugs we discovered in how we do PLT hooking. This may be why you're not seeing any blocks.

**Comment by AndrejLee** [comment]
My emulator's Android version is 8.0.

**Comment by ricardorey10** [comment]
Looking at the actual contents of the trace might give us an idea of what's going on. Could you please provide a snippet from the trace? You can probably do something like `gunzip -c override-main... > outfile` and that should give you the uncompressed contents of the file, which should look something like this:

```
dt
ver|3
id|GeHZavrJSAb
prec|6
pid|23725
arch|i686
os|Android6.0

1|TRACE_START|50204738439|23725|2147483647|1|7460043096821407771
1|TRACE_ANNOTATION|1822|0|-2139357177|-1|-7460043096821407771
1|PROCESS_LIST|48717|18|-8126470|0|0
4|STRING_KEY|3|processes
5|STRING_VALUE|4|com.facebook.loom.sample(23725)
3|MARK_PUSH|5301|0|0|0|0
7|STRING_KEY|6|__name
8|STRING_VALUE|7|Suspending mutator threads
3|MARK_POP|1145|0|0|0|0
```

**Comment by BurntBrunch** [comment]
You're probably getting hit by a double whammy of not-quite-there providers.

3402c092c9821461bda82de1581e810a93ed184b disabled systrace hooking temporarily because we're seeing some issues with hooking we're working through.

Stack trace collection was never implemented on 8.x. We're currently in the process of redoing stack unwinding, so this type of support is much easier to forward-port.
