### ISSUE TITLE
workflow_demo.py stacks and blocks data empty 

### ISSUE THREAD

**Issue by oujunli** [facebookincubator/profilo#25]
I run the sample.apk on OnePlus3 Android 8.0, get trace file, run command analyze the data:
[override-main-11852-2018-6-16T9-45-5-HELSS7eibyu-cs-24bc196c.log](https://github.com/facebookincubator/profilo/files/2107836/override-main-11852-2018-6-16T9-45-5-HELSS7eibyu-cs-24bc196c.log)
```
(env) oujunlideMacBook-Pro:python oujunli$ python3 -m profilo.workflow_demo override-main-11852-2018-6-16T9-45-5-HELSS7eibyu-cs-24bc196c.log stacks sample.apk




(env) oujunlideMacBook-Pro:python oujunli$ python3 -m profilo.workflow_demo override-main-11852-2018-6-16T9-45-5-HELSS7eibyu-cs-24bc196c.log blocks
,IsMain,tid,event,mean,median,std

(env) oujunlideMacBook-Pro:python oujunli$ python3 -m profilo.workflow_demo override-main-11852-2018-6-16T9-45-5-HELSS7eibyu-cs-24bc196c.log syscounters out
(env) oujunlideMacBook-Pro:python oujunli$ ls -l out
total 184
-rw-r--r--  1 oujunli  staff  25646  6 16 11:02 alloc_free_bytes.png
-rw-r--r--  1 oujunli  staff  23876  6 16 11:02 global_alloc_size.png
-rw-r--r--  1 oujunli  staff  15182  6 16 11:02 num_procs.png
-rw-r--r--  1 oujunli  staff  22530  6 16 11:02 proc_cpu_time.png
```
the stacks and blocks data is empty. Is the trace file only contain syscounters data? If so, how can I config the sample apk to enable stacks and blocks?  
Thanks

**Comment by tmelz** [comment]
Stacks are empty because stack tracing isn't currently supported for that OS version (8.0). You can see supported versions here: https://github.com/facebookincubator/profilo/blob/master/java/main/com/facebook/profilo/provider/stacktrace/ArtCompatibility.java#L47

Blocks are empty due to an underlying dependency being disabled currently while we improve stability. Stay tuned.

**Comment by oujunli** [comment]
OK, understood, thanks.

**Comment by tuancoltech** [comment]
@tmelz  Hi, do you have any idea when the blocks will be enabled back again?
Sorry for re-opening.

**Comment by ricardorey10** [comment]
We recently added the capability to collect Android 8 stacks, so this should work now
