### ISSUE TITLE
How mean, median and std of each event are calculated?

### ISSUE THREAD

**Issue by Quang0309** [facebookincubator/profilo#26]
![screenshot from 2018-07-04 09-25-16](https://user-images.githubusercontent.com/32784602/42262838-a9e10498-7f96-11e8-83d0-8df97cfb86ab.png)
For example, i have a method, i place the Start() at the beginning of it and Stop() at the end, does profilo provide me aa inclusive time or exclusive time of this method?

**Comment by aandreyeu** [comment]
Profilo will provide the inclusive time, i.e. wall time delta between start and stop.
