### ISSUE TITLE
How to handle thread info if thead ID reuse?

### ISSUE THREAD

**Issue by oujunli** [facebookincubator/profilo#29]
Read the code `ProcFS.cpp` function `ThreadCache::forEach` and `ThreadCache::forThread`,  the threads info map(`cache_` ) get a thread info though the thread ID, but the thread ID can be reused, if so , the same thread ID is different threads, handle this situation or not? Thanks.

**Comment by ricardorey10** [comment]
We currently do not do any deduplication/disambiguation because the kernel recycles `tid`s on 16 bit overflow, and our traces are never long enough as to reach this limit.
