### ISSUE TITLE
There're a lot of unmeaningful tags in the repo

### ISSUE THREAD

**Issue by simpleton** [facebookincubator/profilo#3]
As title mentioned, there're a lot of  releases and tags on https://github.com/facebookincubator/profilo/releases

**Comment by BurntBrunch** [comment]
Currently, we don't have stable releases, so Travis is set up to create a tag and publish a release from every commit in the repo. We will address this in the future as the API surface stabilizes and we gauge the versioning needs for artifact purposes.
