### ISSUE TITLE
How to remove sample app when building profilo?

### ISSUE THREAD

**Issue by Quang0309** [facebookincubator/profilo#32]
I am have no experience using buck so can you show me how to config the buck script to remove the sample app when building profilo?

**Comment by BurntBrunch** [comment]
Apologies for the delay on this.
Are you specifically asking how to remove the sample app activity from the .aar or something else?
I think that's an oversight we can easily fix, if that's your issue :)

**Comment by Quang0309** [comment]
Yes i want to remove the sample app from the .aar

**Comment by BurntBrunch** [comment]
The mentioned commit solves this. Please reopen if there's anything else left to remove :)
