### ISSUE TITLE
Stack unwinding for Android 8.0 and above is not supported

### ISSUE THREAD

**Issue by deadmoto** [facebookincubator/profilo#33]
Stack unwinding is not supported for android 8.0 and above as of now.
Please, keep this issue open as a placeholder for people to subscribe to.

**Comment by aandreyeu** [comment]
Android 8.0 and 9.0 coverage is surely in plan.

**Comment by ricardorey10** [comment]
I added 8.x support in daed61c01f68966415460821dab1bdca6f2afcee and 94eb24c53a051aa4eec18a8b738fccac2baabe9d.

9.x is yet to come, but I'll close this issue now, as it is only tracking 8.0.
