### ISSUE TITLE
Failed to setup and run workflow_demo.py

### ISSUE THREAD

**Issue by am5a03** [facebookincubator/profilo#36]
Followed the guide, but it failed to install related dependencies
```
virtualenv -p python3 env
source env/bin/activate
pip3 install -r requirements.txt
```
Here is an installation log:
[install.log](https://github.com/facebookincubator/profilo/files/2497784/install.log)

I tried to install NumPy globally, it success, but when invoking workflow_demo:
```
(env) raymond@Raymonds-MBP:~/workspace/profilo/python$ python3 -m profilo.workflow_demo --help
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/raymond/workspace/profilo/python/profilo/workflow_demo.py", line 26, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by aandreyeu** [comment]
Looking into the supplied `install.log` I see that you've got few errors during the numpy installation. Could you double-check if your numpy is set correctly and try to resolve the installation issues.

**Comment by am5a03** [comment]
Thanks. It installed successfully on my Mac, running on Mojave, by using the latest versions of pandas and numpy.

However, on my Debian 9, both pandas and numpy can be installed successfully with the versions specified in `requirements.txt` 😅
