### ISSUE TITLE
pull_last_trace get error

### ISSUE THREAD

**Issue by 294485329peng** [facebookincubator/profilo#37]
i install demo.apk and start trace.
then run python3 -m profilo.profilo pull_traces --last com.facebook.profilo.sample
error msg: Bad magic number for file header. Exiting

**Comment by aandreyeu** [comment]
Could you show what's in your demo's cace dir by running:
```
adb root
adb shell ls -Ral /data/data/com.facebook.profilo.sample/cache
```

**Comment by 294485329peng** [comment]
> Could you show what's in your demo app's cache dir by running:
> 
> ```
> adb root
> adb shell ls -Ral /data/data/com.facebook.profilo.sample/cache
> ```

like this.
![a](https://user-images.githubusercontent.com/11804394/49706930-cb71e100-fc63-11e8-9e3c-45bebcf9a66f.jpg)

**Comment by aandreyeu** [comment]
How consistent this issues is? if you record a different trace?
The error most likely mean that the file is not a valid archive which should not be the case.
