### ISSUE TITLE
What IDE/editor do you use to develop/debug the project ?

### ISSUE THREAD

**Issue by wuairc** [facebookincubator/profilo#40]
I want to read the source code to figure out what the docs are missing, but I can't use Android Studio/CLion/PyCharm to read Java/C++/Python code, there are unresolved reference everywhere.

So very curious about what IDE/editor you use to develop the project? How do you debug it? Using BUCK build and docker set an barrier for people like me to read the code or even contribute to the project.

**Comment by aandreyeu** [comment]
I can recommend Nuclide: https://nuclide.io/ as I personally use it to work on the project. However, It's also not perfect for reference navigation either.
