### ISSUE TITLE
Support for x86_64 and arm64 architectures

### ISSUE THREAD

**Issue by rahul-a** [facebookincubator/profilo#44]
I'm planning to use Profilo on prod builds, and was wondering if there is a roadmap to support x86_64 and arm64 ABIs?

I was able to build from source for arm64 and x86_64 but I'm getting `CLASS_LOAD_FAILED` in type for every byte entry being logged from my flows.

Also, would it be advisable to compile for these ABIs at the moment?

**Comment by BurntBrunch** [comment]
We actually have a 64-bit build internally, I'm looking into enabling it in this repository.
Bear in mind that there's no stack trace support yet, only atrace capture will work.

**Comment by rahul81491** [comment]
@BurntBrunch sure, is there any roadmap to enable stacktrace support on 64-bit?

**Comment by rahul-a** [comment]
@BurntBrunch sure, are there any plans to add support for stack traces on 64-bit ABIs in the near future?

**Comment by BurntBrunch** [comment]
> are there any plans to add support for stack traces on 64-bit ABIs in the near future?

Depends on how near we're talking. :) It's definitely something we want to get to but probably won't happen by the end of the year. Early 2020 is most likely.

**Comment by Fortisque** [comment]
Hey stack traces should be working for OS 9 64 bit following https://github.com/facebookincubator/profilo/commit/3c93dccc2d1aff0fb453a2c6fb3854934fcdec12. That commit was awhile back, apologies about not updating this issue sooner.

I'll close this for now, but feel free to re-open if we are still missing something.
