### ISSUE TITLE
Unknown IDs in flame graph when stacks are produced

### ISSUE THREAD

**Issue by amanjeetsingh150** [facebookincubator/profilo#48]
Getting some blocks as IDs only (in flame graph blocks) rather than full method names which we produce through stack output ?

**Comment by ricardorey10** [comment]
Do you have an example of this?

If you could provide the raw trace and an image for the flame graph with the unknown IDs that would be great =)

**Comment by amanjeetsingh150** [comment]
Yes following is the screenshot:
<img width="1083" alt="Screenshot 2019-10-19 at 5 08 11 PM" src="https://user-images.githubusercontent.com/12881364/67144348-181a4580-f293-11e9-96f2-69332417c2bf.png">

In case of ID only blocks the trace only consist of this number rather than full name of method with class like the rest?

**Comment by amanjeetsingh150** [comment]
@BurntBrunch @ricardorey10 @yangshun Hey, I inspected around these unknown IDs and inferred that these were actually the framework code from google like maps in my case which definitely can be a framework code: `Lcom/google/maps/api/android/lib6/gmm6/vector/bg` .  So, this may also be treated as a framework frame and added as a prefix possibility in <a href="https://github.com/facebookincubator/profilo/blob/master/cpp/profiler/JavaBaseTracer.h#L44">here</a> in JavaBaseTrace.h .

Should I raise a PR for this?

**Comment by amanjeetsingh150** [comment]
Issue resolved in following PR: #49 closing the issue. Changelog <a href="https://github.com/facebookincubator/profilo/commit/596b1a7c1c0f4bcd7caade39f254bb6f92978939"/>here</a>
