### ISSUE TITLE
Missing README in python/demos

### ISSUE THREAD

**Issue by ericleong** [facebookincubator/profilo#5]
The [README](https://github.com/facebookincubator/profilo/#demos) says

> A demo script can be found in `python/profilo/workflow_demo.py`. It contains examples of simple
analysis that can be run on Profilo traces. For more information see the README
`python/demos/README.md`

Unfortunately, [`python/demos`](https://github.com/facebookincubator/profilo/tree/master/python/demos) is missing the README. Perhaps [`trace-processing.md`](https://github.com/facebookincubator/profilo/blob/master/docs/trace-processing.md) is the file the README is intended to link to?

**Comment by BurntBrunch** [comment]
Thanks, fixed the readme to point to the website.
