### ISSUE TITLE
Missing framework frames information in stacktraces (pre-lollipop devices)

### ISSUE THREAD

**Issue by rahul-a** [facebookincubator/profilo#52]
Dalvik tracer doesn't inherit from the JavaBaseTracer, hence there is no symbolication for framework frames at the time of flushing stack traces when running on Android 4.x or below.

**Comment by rahul-a** [comment]
Hello,
am I missing something here or is the Dalvik tracer is supposed to not inherit from JavaBaseTracer?

**Comment by BurntBrunch** [comment]
Hi @rahul-a, you are correct, this is an oversight. Let me take a look at the PR :)
