### ISSUE TITLE
How to keep collect stack safety in profiler?

### ISSUE THREAD

**Issue by ohmerhe** [facebookincubator/profilo#56]
Hi, as i know, if we want to safely walk stack directly in current thread, we must make some situation to satisfy 'walkable' state, such as GC is not active.
I do not find any code to permit for it, so do i missed something in the code?
And i noticed that profilo receive SIGSEGV/SIGBUS signal. Is this just for the exception of memory which produced  by something like GC?

**Comment by BurntBrunch** [comment]
Let me see if I can address your questions:

> we must make some situation to satisfy 'walkable' state

I believe you're referring to "safe points" or "suspension points" in ART lingo. 

Profilo's unwinding does not require suspension points and instead intrusively unwinds the managed Java stack by chasing pointers from a known ABI (AOSP's ABI to be precise). As a result, it is _fallible_ and failures are expected (we log error entries when we fail to unwind). This fallibility is also why we handle SIGSEGV and SIGBUS - we may fail for any number of reasons (malformed stack, unknown ABI) and don't want to take down the process as a result.

The upside of doing things intrusively in this way is that we can use perform async-signal-safe unwinding using setitimer, which in turn gives us CPU-time-biased stack traces. We also avoid any systemic bias in suspension point unwinding (there are a few papers out there on why intrusive unwinding is less biased).

Hope this helps!
