### ISSUE TITLE
NativeTracer

### ISSUE THREAD

**Issue by Colibrow** [facebookincubator/profilo#80]
Hi, I noticed that the latest commit [with/without native_tracer](https://github.com/facebookincubator/profilo/commit/800ea2eeb3ad5b74d1c5a4f0fe99c0e16e4e03d9) and want to know if there is an efficient way to get native stacks(cfi on arm32 or framepointer on arm64 maybe), also curious about if the implementation would be open-source in future.

**Comment by aandreyeu** [comment]
Android's [Libunwindstack](https://cs.android.com/android/platform/superproject/+/master:system/unwinding/libunwindstack/?q=libunwindstack) is probably the best unwinder for the platform I know of. It's also capable of getting mixed stacks. Our implementation of `NativeTracer` is currently experimental and we don't have concrete plans to move it to OSS profilo yet.
