### ISSUE TITLE
profilo unwind cannot work on 6.0 with arm64 devices

### ISSUE THREAD

**Issue by Colibrow** [facebookincubator/profilo#85]
**Describe the bug**

profilo unwind cannot work on 6.0 with arm64 devices

**Env:**

  ​	device:  Nexus 6P
  ​	flash image: https://dl.google.com/dl/android/aosp/angler-mda89d-factory-9f001626.zip
  ​	arch: arm64-v8a

**Steps To Reproduce:**
        adb install sample.apk
        startTrace

**Logs**

> 01-01 07:01:13.046 6713-6732/com.facebook.profilo.sample I/OpenGLRenderer: Initialized EGL, version 1.4
01-01 07:01:16.256 6713-6713/com.facebook.profilo.sample W/Profilo/TraceControl: START PROFILO_TRACEID: DkRO9tTuJww
01-01 07:01:16.263 6713-6745/com.facebook.profilo.sample D/SoLoader: About to load: libprofilo_atrace.so
01-01 07:01:16.263 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_atrace.so not found on /data/data/com.facebook.profilo.sample/lib-main
01-01 07:01:16.263 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_atrace.so found on /data/app/com.facebook.profilo.sample-1/lib/arm64
01-01 07:01:16.264 6713-6745/com.facebook.profilo.sample D/SoLoader: Not resolving dependencies for libprofilo_atrace.so
01-01 07:01:16.271 6713-6745/com.facebook.profilo.sample D/Profilo/atrace: Applying FaultHandler workaround
01-01 07:01:16.271 6713-6745/com.facebook.profilo.sample D/SoLoader: Loaded: libprofilo_atrace.so
01-01 07:01:16.280 6713-6745/com.facebook.profilo.sample D/SoLoader: About to load: libprofilo_stacktrace.so
01-01 07:01:16.280 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_stacktrace.so not found on /data/data/com.facebook.profilo.sample/lib-main
01-01 07:01:16.280 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_stacktrace.so found on /data/app/com.facebook.profilo.sample-1/lib/arm64
01-01 07:01:16.280 6713-6745/com.facebook.profilo.sample D/SoLoader: Not resolving dependencies for libprofilo_stacktrace.so
01-01 07:01:16.282 6713-6745/com.facebook.profilo.sample D/SoLoader: Loaded: libprofilo_stacktrace.so
01-01 07:01:16.311 6713-6745/com.facebook.profilo.sample D/Profilo/ArtCompatibility: Cpp stack child exited: 0 status: 0 (failure) signalled: 1 signal: 11
01-01 07:01:16.313 6713-6745/com.facebook.profilo.sample I/Profilo/Profiler: Starting profiling timers w/sample rate 10
01-01 07:01:16.314 6713-6745/com.facebook.profilo.sample D/SoLoader: About to load: libprofilo_systemcounters.so
01-01 07:01:16.314 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_systemcounters.so not found on /data/data/com.facebook.profilo.sample/lib-main
01-01 07:01:16.314 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_systemcounters.so found on /data/app/com.facebook.profilo.sample-1/lib/arm64
01-01 07:01:16.314 6713-6745/com.facebook.profilo.sample D/SoLoader: Not resolving dependencies for libprofilo_systemcounters.so
01-01 07:01:16.316 6713-6745/com.facebook.profilo.sample D/SoLoader: Loaded: libprofilo_systemcounters.so
01-01 07:01:16.318 6713-6745/com.facebook.profilo.sample D/SoLoader: About to load: libprofilo_threadmetadata.so
01-01 07:01:16.318 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_threadmetadata.so not found on /data/data/com.facebook.profilo.sample/lib-main
01-01 07:01:16.318 6713-6745/com.facebook.profilo.sample D/SoLoader: libprofilo_threadmetadata.so found on /data/app/com.facebook.profilo.sample-1/lib/arm64
01-01 07:01:16.318 6713-6745/com.facebook.profilo.sample D/SoLoader: Not resolving dependencies for libprofilo_threadmetadata.so
01-01 07:01:16.322 6713-6745/com.facebook.profilo.sample D/SoLoader: Loaded: libprofilo_threadmetadata.so
01-01 07:01:17.778 6713-6713/com.facebook.profilo.sample W/Profilo/TraceControl: STOP PROFILO_TRACEID: DkRO9tTuJww

Hi, @Fortisque could you help to solve this version of unwind? 
Many thanks, plz.:)

**Comment by Fortisque** [comment]
Hi, we're not convinced the 8 and below 64 bit underwinders are working. I thought I saw the x86_64 version working on my emulator for 7.0 which is why we added the changes, but unfortunately it doesn't seem to be working for arm yet. Sorry about that, I'm not sure when we will be able to get it working, looks like it wasn't as easy as we thought

**Comment by Colibrow** [comment]
Yup. I think the 8 below arm64 bit is not that important and I just give a little test on the lower version.
Never mind, just let it go.
