### ISSUE TITLE
Is there a way to generate file that can be analyze by perfetto (systrace file)?

### ISSUE THREAD

**Issue by jinweihan2021** [facebookincubator/profilo#98]
Is there a way to generate file that can be analyze by perfetto (systrace file)?

**Comment by BurntBrunch** [comment]
(Sorry about not getting to this earlier!)

No, there's unfortunately no systrace export. However, it wouldn't be hard to write given our python parser - we already build up "blocks" and "threads" and it would be just a matter of exporting the data model in the formats that perfetto expects.

I'd be happy to walk you through how to do that in more detail, if you're interested. :)
